### ISSUE TITLE
Sketch crashes on export

### ISSUE THREAD

**Issue by AnkeSes** [sketch-hq/print-export-sketchplugin#25]
When I export a page to PDF, Sketch crashes and the exported PDF gives an error when I try to open it.

Sketch 61.2

**Comment by satoshionoda** [comment]
Same Here

**Comment by christianklotz** [comment]
Thank you for reporting, looking into it

**Comment by swithey** [comment]
I'm experiencing this as well. Version 62 (91390).

**Comment by Tafkadasoh** [comment]
I have the same issue!

I found out that the reason for the crash is the presence of any symbol. If I detach all contents for all symbols, then the export does not crash.

**Comment by dreu91** [comment]
Just reporting that the crash is happening in Version 63.1 (92452) as well.

**Comment by Tafkadasoh** [comment]
In the meantime I've found out that the crash is already fixed, but they have just forgotten to release a new version! If you follow the installation instruction section "From source" then you'll get a local version that does not crash anymore!

**Comment by lazing** [comment]
> In the meantime I've found out that the crash is already fixed, but they have just forgotten to release a new version! If you follow the installation instruction section "From source" then you'll get a local version that does not crash anymore!

glad to hear. but when you decide to release a new version?

**Comment by bomberstudios** [comment]
Sorry about this, just pushed a new version. Please let me know if that fixes it!

**Comment by heilmaem** [comment]
Still happening for me @bomberstudios. 

"There was an error opening this document. The file is damaged and cannot be repaired."

**Comment by jannnebk** [comment]
@bomberstudios This started to happen with the latest Sketch update (66.1) for me

**Comment by MalteVoelkner** [comment]
Still happenning to me, and I don’t know how to install „From source“. @christianklotz can you provide an alternative downloadlink to the newer version? Sketch crashes without an error message when exporting, with or without Symbols. Thanks.

**Comment by bomberstudios** [comment]
## QA Notes

Make sure the plugin works as expected, especially on Catalina where I haven't tested the fix (should work, but you know how it is...)

[print-export.sketchplugin.zip](https://github.com/sketch-hq/print-export-sketchplugin/files/4804144/print-export.sketchplugin.zip)

**Comment by bomberstudios** [comment]
This has been fixed in v1.0.10, which is out now.

Closing!
